### ISSUE TITLE
Generated links are incorrect in some cases

### ISSUE THREAD

**Issue by jskeet** [aip-dev/site-generator#47]
In the current [AIP-193 Markdown](https://raw.githubusercontent.com/aip-dev/google.aip.dev/7fedf83b3d2f1e8bac7958793b54d67add62e5db/aip/general/0193.md) we have:

```text
- For how to retry errors in client libraries, see [AIP-4221][].
```

The site generator creates a link for that to https://google.aip.dev/client-libraries/4221.md, whereas it should be https://google.aip.dev/client-libraries/4221 (no .md)

This can be fixed by making the link explicit, but if implicit links don't work then there's no point in having them.

**Comment by shwoodard** [comment]
I'll fix this but the generated HTML has the right link inline so there isn't a broken link.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/34149/167941362-7de9184a-87aa-45be-8776-7e073c7652f1.png">

**Comment by shwoodard** [comment]
OIC, this is because it's explicitly specified.
